language: scala
git:
  depth: false
matrix:
  include:
    - os: linux
      jdk: openjdk11
      scala: 2.12.8
    - os: linux
      jdk: openjdk8
      scala: 2.12.8
script:
  - travis_wait 40 sbt -no-colors ++$TRAVIS_SCALA_VERSION -J-Xms2g -J-Xmx2g -J-XX:MaxMetaspaceSize=512m clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
